import { backend } from './backend';
export async function exportCandidate(id: string, format: 'pdf'|'csv'|'json') {
  const payload=await backend('candidate-export',{},id);const record=payload.evidence;const candidate=record.candidate;
  let bytes:Uint8Array;let mime:string;
  if(format==='json'){bytes=new TextEncoder().encode(JSON.stringify(payload,null,2));mime='application/json';}
  else if(format==='csv'){const safe=(value:unknown)=>'"'+String(value??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const rows=[['site','action','period','component','raw','normalised','weight','points','source','config','rule','hash','status'],...candidate.components.map((component:any)=>[candidate.siteId,candidate.action,candidate.period,component.code,component.raw,component.normalised,component.weight,component.contribution,component.sourceRef,record.config.id,candidate.serviceEvidence.rule?.id,record.hash,'SYNTHETIC'])];bytes=new TextEncoder().encode(rows.map(row=>row.map(safe).join(',')).join('\r\n'));mime='text/csv';}
  else{const {PDFDocument,StandardFonts,rgb}=await import('pdf-lib');const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);let page=pdf.addPage([595,842]);let y=794;const line=(text:string,size=11)=>{const clean=text.replace(/[^\x20-\x7E]/g,' ');const words=clean.split(' ');let buffer='';for(const word of words){if(font.widthOfTextAtSize((buffer+' '+word).trim(),size)>495&&buffer){if(y<55){page=pdf.addPage([595,842]);y=794;}page.drawText(buffer,{x:50,y,size,font,color:rgb(.094,.094,.102)});y-=size+7;buffer=word;}else buffer=(buffer+' '+word).trim();}if(buffer){if(y<55){page=pdf.addPage([595,842]);y=794;}page.drawText(buffer,{x:50,y,size,font});y-=size+7;}};line('NETONE | INVESTMENT CARD',18);line('SYNTHETIC - ADVISORY - NO CAPITAL APPROVAL',10);line(`${candidate.siteId} | ${candidate.action}`,15);line(`Period ${candidate.period}; cost USD ${candidate.estimatedCost}; score ${candidate.score??'WITHHELD'}`);line(candidate.reason);line(`Model ${candidate.modelVersion}; config ${record.config.name} v${record.config.version}`);for(const component of candidate.components)line(`${component.code}: raw ${component.raw??'missing'}, normalised ${component.normalised??'withheld'}, weight ${component.weight}%, contribution ${component.contribution??'withheld'}`);line(`Rule ${candidate.serviceEvidence.rule?.id??'none'} version ${candidate.serviceEvidence.rule?.version??'none'}`);line(`Source ${candidate.sourceRef}; ${record.source.incidents.length} linked incident snapshots; ${record.source.evaluations.length} retained rule evaluations.`);line(`Evidence ${record.id}; SHA-256 ${record.hash}`,9);line(`Saved by ${record.actor} at ${record.at}; exported by ${payload.exportedBy}`);line('Refer to the JSON evidence export for the complete source, incident timelines and rule chain. Intervention effects are unvalidated.');bytes=await pdf.save();mime='application/pdf';}
  const blob=new Blob([bytes as BlobPart],{type:mime});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`netone-candidate-${id}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
