import type { Obligation } from '../data/obligations.js';
import type { Candidate } from './investments.js';
export interface Cell {id:string;siteId:string;service:string;technology:string;demo:true}
export interface CellMeasurement {id:string;cellId:string;metric:string;period:string;windowStart:string;windowEnd:string;numerator:number;denominator:number;unit:'%';quality:'COMPLETE'|'PARTIAL'|'STALE';sourceRef:string;protocolRef:string;demo:true}
export interface Finding {id:string;obligation:Obligation;cell:Cell|null;measurement:CellMeasurement|null;value:number|null;state:'INSUFFICIENT_EVIDENCE'|'UNDER_REVIEW'|'POTENTIAL_EXCEPTION'|'NO_EXCEPTION_OBSERVED'|'REVIEWER_CONFIRMED';reason:string;at:string;reviewer?:string;reviewNote?:string;reviewAt?:string}
export interface Option {id:string;kind:'BUILD'|'UPGRADE'|'SHARE'|'MAINTAIN'|'DEFER';actionCode:string;cost:number|null;basis:string;currency:'USD';counterpart:string;infrastructureType:string;spareCapacityEvidence:string;technicalFeasibility:'UNKNOWN'|'SUPPORTED'|'UNSUPPORTED';commercialFeasibility:'UNKNOWN'|'SUPPORTED'|'UNSUPPORTED';setupCost:number|null;recurringCost:number|null;accessDependencies:string;requestStatus:string;agreementRef:string;approvalRef:string;requestDate?:string;holidayCalendarRef?:string;holidayDates?:string[];deadline:string|null;deadlineSource:string;owner:string;businessCase:BusinessCase}
export interface BusinessCase {incrementalContribution:{low:number|null;base:number|null;high:number|null};opexSavings:number|null;recurringCosts:number|null;implementationMonths:number|null;horizonMonths:number|null;basis:string;assumptions:string;sourceRef:string;reviewer:string;operationalImprovement:string;measurementPlan:string;deferImpact:string}
export interface CorrectiveCase {id:string;siteId:string;cellIds:string[];service:string;period:string;obligationId:string;obligationSnapshot:Obligation;finding:Finding;incidentIds:string[];incidentSnapshots:unknown[];diagnosis:{cause:'UNKNOWN'|'POWER'|'CAPACITY'|'BACKHAUL'|'MAINTENANCE';status:'SUSPECTED'|'CONFIRMED';evidenceRefs:string[];note:string};owner:string;dueDate:string|null;dueSource:string;options:Option[];selectedOptionId:string|null;engineeringReview:{actor:string;at:string;note:string}|null;regulatoryReview:{actor:string;at:string;note:string}|null;status:'DRAFT'|'DIAGNOSIS'|'OPTIONS'|'SUBMITTED'|'REVIEWED'|'IMPLEMENTING'|'IMPLEMENTED'|'VERIFIED';implementationRef:string;measurementPlan:string;outcome:{measurementId:string;result:number;note:string;actor:string;at:string}|null;events:{actor:string;at:string;action:string;note:string}[];demo:true}
export interface PilotState {version:1;obligations:Obligation[];cells:Cell[];measurements:CellMeasurement[];findings:Finding[];cases:CorrectiveCase[];privacyIncidents:{id:string;status:'OPEN'|'UNDER_REVIEW'|'CLOSED';note:string;owner:string;events:{actor:string;at:string;note:string}[]}[]}
export const unknownBusinessCase=():BusinessCase=>({incrementalContribution:{low:null,base:null,high:null},opexSavings:null,recurringCosts:null,implementationMonths:null,horizonMonths:null,basis:'USD nominal incremental monthly assumptions',assumptions:'Benefits unknown; site contribution is not incremental value',sourceRef:'',reviewer:'',operationalImprovement:'Unknown',measurementPlan:'',deferImpact:'Unknown'});
export function evaluateObligation(obligation:Obligation,cell:Cell|null,measurement:CellMeasurement|null,at:string):Omit<Finding,'id'> {
 let reason='',state:Finding['state']='INSUFFICIENT_EVIDENCE',value:number|null=null;
 if(!obligation.sourceVerified){state='UNDER_REVIEW';reason='Authoritative provision unavailable; evaluation disabled';}
 else if(!cell||!measurement||obligation.level!=='CELL'||measurement.cellId!==cell.id||measurement.metric!==obligation.metric||!obligation.technologies.includes(cell.technology)||cell.service!==obligation.service){reason='Applicable cell-level KPI evidence unavailable; site monthly aggregates cannot substitute';}
 else if(!['dsasr','dsdr','cellAvailability'].includes(measurement.metric)){reason='Measurement evaluator not implemented for this KPI; evidence insufficient';}
 else if(measurement.metric==='cellAvailability'&&(measurement.denominator!==24||Date.parse(measurement.windowEnd)-Date.parse(measurement.windowStart)!==86400000)){reason='Cell availability requires a daily 24-hour observation and denominator; monthly site aggregates cannot substitute';}
 else if(measurement.quality!=='COMPLETE'||measurement.denominator<=0||measurement.numerator<0||measurement.numerator>measurement.denominator||!Number.isFinite(measurement.numerator)||!Number.isFinite(measurement.denominator)||measurement.unit!==obligation.unit||!Number.isFinite(Date.parse(measurement.windowStart))||!Number.isFinite(Date.parse(measurement.windowEnd))||Date.parse(measurement.windowEnd)<=Date.parse(measurement.windowStart)||!measurement.protocolRef||!measurement.sourceRef){reason='Incomplete, stale, invalid or missing measurement protocol/counters';}
 else if(obligation.applicability!=='APPLICABLE'||obligation.reviewStatus!=='REVIEWED'||!obligation.reviewNote||!obligation.effectiveFrom||measurement.windowStart.slice(0,10)<obligation.effectiveFrom||(obligation.effectiveTo&&measurement.windowEnd.slice(0,10)>obligation.effectiveTo)){state='UNDER_REVIEW';reason='Legal interpretation, applicability, effective interval and sampling protocol require owner review';}
 else {value=measurement.numerator/measurement.denominator*100;const exception=obligation.comparator==='>='?value<obligation.threshold!:obligation.comparator==='<='?value>obligation.threshold!:false;state=exception?'POTENTIAL_EXCEPTION':'NO_EXCEPTION_OBSERVED';reason='Screening comparison for reviewed sampling protocol only; no statutory compliance or fine determination';}
 return {obligation:structuredClone(obligation),cell:structuredClone(cell),measurement:structuredClone(measurement),value,state,reason,at};
}
export function businessValue(option:Option){const b=option.businessCase;const required=[option.cost,b.incrementalContribution.low,b.incrementalContribution.base,b.incrementalContribution.high,b.opexSavings,b.recurringCosts,b.implementationMonths,b.horizonMonths];if(required.some(x=>x===null||!Number.isFinite(x))||b.basis!=='USD nominal incremental monthly assumptions'||!b.sourceRef||!b.reviewer||!b.measurementPlan||b.horizonMonths!<=b.implementationMonths!||b.incrementalContribution.low!>b.incrementalContribution.base!||b.incrementalContribution.base!>b.incrementalContribution.high!)return {status:'UNKNOWN',net:null,assumption:'Compatible reviewed incremental cash-flow assumptions and measurement plan required; no ROI inferred.'};const months=b.horizonMonths!-b.implementationMonths!;return {status:'ILLUSTRATIVE',net:{low:(b.incrementalContribution.low!+b.opexSavings!-b.recurringCosts!)*months-option.cost!,base:(b.incrementalContribution.base!+b.opexSavings!-b.recurringCosts!)*months-option.cost!,high:(b.incrementalContribution.high!+b.opexSavings!-b.recurringCosts!)*months-option.cost!},assumption:'Undiscounted incremental net cash flow, constant monthly assumptions after implementation; no tax/inflation/discounting or automatic avoided fines. Failure cost is included in OPEX; do not add it again.'}}
export function supportCandidate(candidate:Candidate,cases:CorrectiveCase[],currentObligations?:Obligation[]):Candidate {const cause=({capacity:'CAPACITY',resilience:'POWER',backhaul:'BACKHAUL',maintenance:'MAINTENANCE'} as Record<string,string>)[candidate.actionCode];const record=cases.find(c=>c.siteId===candidate.siteId&&c.period===candidate.period&&c.diagnosis.cause===cause&&c.diagnosis.status==='CONFIRMED'&&c.diagnosis.evidenceRefs.length&&c.engineeringReview&&c.selectedOptionId&&c.options.some(o=>o.id===c.selectedOptionId&&o.actionCode===candidate.actionCode&&o.technicalFeasibility==='SUPPORTED'));const option=record?.options.find(o=>o.id===record.selectedOptionId);const ready=!!record&&!!record.regulatoryReview&&option?.cost!==null&&!!option&&option.cost>0&&(option.kind!=='SHARE'||option.commercialFeasibility==='SUPPORTED'&&!!option.agreementRef&&!!option.approvalRef);return {...candidate,...(ready&&option?{estimatedCost:option.cost!,costBasis:option.basis}:{}),evidenceSufficiency:record?'Cause evidence and engineering review linked':`Diagnosis required: ${cause.toLowerCase()} cause not established by screening metrics`,engineeringStatus:record?'VALIDATED':'NOT_REVIEWED',reviewReady:ready,serviceAssuranceSupported:ready&&(!currentObligations||currentObligations.some(o=>o.id===record.obligationId&&o.version===record.obligationSnapshot.version&&o.applicability==='APPLICABLE'&&o.reviewStatus==='REVIEWED'))&&record.obligationSnapshot.sourceVerified&&record.obligationSnapshot.applicability==='APPLICABLE'&&record.finding.state==='REVIEWER_CONFIRMED'}}

export function sharingResponseDeadline(requestDate:string,holidays:string[],calendarRef:string):string|null {if(!calendarRef||!/^\d{4}-\d{2}-\d{2}$/.test(requestDate)||!Number.isFinite(Date.parse(requestDate))||new Date(requestDate).toISOString().slice(0,10)!==requestDate||holidays.some(d=>!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d))))return null;const date=new Date(requestDate+'T00:00:00Z');let count=0;for(let days=0;days<366&&count<14;days++){date.setUTCDate(date.getUTCDate()+1);if(![0,6].includes(date.getUTCDay())&&!holidays.includes(date.toISOString().slice(0,10)))count++;}return count===14?date.toISOString().slice(0,10):null;}
