import assert from 'node:assert/strict';
const base=process.env.BASE_URL||'http://127.0.0.1:5175';
async function req(action,body,cookie='',id){const r=await fetch(`${base}/api/netone?action=${action}${id?'&id='+encodeURIComponent(id):''}`,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Origin:base,Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
const roles={};for(const role of ['finance','admin','network','regulatory','executive']){const login=await req('login',{username:role,password:'netone-local-demo'});assert.equal(login.status,200);roles[role]=login.cookie;}
const ws=async()=>(await req('workspace',undefined,roles.admin)).data.workspace;
const command=async(action,body,role='admin')=>{const w=await ws();return req(action,{...body,revision:w.revision},roles[role]);};
let w=await ws();assert.equal(w.sites.length,100);assert.ok(w.rules.length>=2);assert.ok(w.sites.every(site=>site.networkHistory.length>=6));assert.equal(w.sites[0].networkHistory.find(row=>row.period==='2026-09').utilisation,null);
assert.equal((await command('incidents',{operation:'create'},'finance')).status,403);
const created=await command('incidents',{operation:'create',siteId:'N005',type:'Synthetic fault test',severity:'HIGH',impact:'Fictional recurring service interruption',estimatedBurden:600,note:'Observed synthetic opening evidence',actor:'forged'},'network');assert.equal(created.status,200);const incident=created.data.incident;assert.equal(incident.events[0].actor,'network');
assert.equal((await command('incidents',{operation:'transition',id:incident.id,state:'CLOSED',note:'Skip states'},'network')).status,400);
for(const state of ['ACKNOWLEDGED','INVESTIGATING','FIELD_RESPONSE','RESTORED','VERIFIED','CLOSED'])assert.equal((await command('incidents',{operation:'transition',id:incident.id,state,note:'Validated synthetic transition'},'network')).status,200);
w=await ws();assert.equal(w.incidents.find(value=>value.id===incident.id).events.length,7);
const rule=await command('rules',{operation:'create',code:'DEMO-TEST-DOWNTIME',metric:'downtimeHours',comparator:'>',threshold:8,effectiveFrom:'2026-08-01',effectiveTo:'2026-10-01',source:'Fictional demonstration threshold'},'regulatory');assert.equal(rule.status,200);const ruleId=rule.data.rule.id;
assert.equal((await command('rules',{operation:'activate',id:ruleId},'regulatory')).status,400);assert.equal((await command('rules',{operation:'review',id:ruleId,note:'Reviewed as demonstration only'},'regulatory')).status,200);assert.equal((await command('rules',{operation:'activate',id:ruleId},'regulatory')).status,200);
const evaluated=await command('rules',{operation:'evaluate',period:'2026-09'},'regulatory');assert.equal(evaluated.status,200);w=await ws();const historical=structuredClone(w.evaluations.filter(value=>value.ruleId===ruleId));assert.ok(historical.length>=100);assert.equal((await command('rules',{operation:'retire',id:ruleId},'regulatory')).status,200);w=await ws();for(const event of historical)assert.deepEqual(w.evaluations.find(value=>value.id===event.id),event);
assert.equal((await command('config',{operation:'create'},'executive')).status,403);
const config=await command('config',{operation:'create',name:'Commercial sensitivity test',minimumScore:2,weights:{demand:15,growth:10,commercial:60,reliability:5,service:5,opex:5,strategy:0}},'finance');assert.equal(config.status,200);assert.equal((await command('config',{operation:'activate',id:config.data.config.id},'finance')).status,403);assert.equal((await command('config',{operation:'activate',id:config.data.config.id})).status,200);
const filters={period:'2026-09',region:'All',technology:'All',state:'All'};const study=await req('sensitivity',{filters},roles.finance);assert.equal(study.status,200);assert.equal(study.data.result.baselines.length,5);assert.ok(study.data.result.thresholds.length>=3);
const scored=await command('score',{filters},'finance');assert.equal(scored.status,200);assert.equal(scored.data.run.candidateCount,400);w=await ws();assert.ok(w.evidence.length>=400);const evidenceId=scored.data.run.recordIds[0];const before=(await req('candidate-evidence',undefined,roles.finance,evidenceId)).data.evidence;assert.equal(before.config.id,config.data.config.id);assert.equal(before.hash.length,64);
const row={external_ref:'source-test-005',canonical_ref:'N005',name:w.sites[4].name,region:w.sites[4].region,technology:w.sites[4].technology,latitude:w.sites[4].latitude,longitude:w.sites[4].longitude,period:'2026-09',utilisation:60,growth:5,availability:99.5,faults:1,trafficGB:9999,downtimeHours:3.6,capex:120000,opex:3000,contribution:20000,failureCost:200,currency:'USD',basis:'Nominal synthetic monthly aggregates',demo:true};
const payload={key:'integration-test-'+Date.now(),source:'test-import',format:'json',rows:[row,{...row,external_ref:'invalid',msisdn:'not-stored'},{...row,external_ref:'real',demo:false}]};const imported=await command('imports',payload);assert.equal(imported.status,200);assert.equal(imported.data.run.accepted,1);assert.equal(imported.data.run.rejected,2);const count=(await ws()).imports.length;assert.equal((await command('imports',payload)).data.run.id,imported.data.run.id);assert.equal((await ws()).imports.length,count);assert.equal((await command('imports',{...payload,rows:[{...row,trafficGB:1}]})).status,409);
assert.equal((await command('imports',payload,'network')).status,403);const after=(await req('candidate-evidence',undefined,roles.finance,evidenceId)).data.evidence;assert.deepEqual(after,before,'saved evidence must not change after imports');
const exported=await req('candidate-export',{},roles.finance,evidenceId);assert.equal(exported.status,200);assert.equal(exported.data.evidence.hash,before.hash);assert.equal((await req('candidate-export',{},roles.executive,evidenceId)).status,403);
const submitted=await command('reviews',{operation:'submit',subjectType:'candidate',subjectId:evidenceId,note:'Request technical evidence review'},'finance');assert.equal(submitted.status,200);assert.equal((await command('reviews',{operation:'transition',id:submitted.data.review.id,status:'REVIEWED',note:'Skip review'},'network')).status,400);assert.equal((await command('reviews',{operation:'transition',id:submitted.data.review.id,status:'IN_REVIEW',note:'Checking evidence'},'network')).status,200);assert.equal((await command('reviews',{operation:'transition',id:submitted.data.review.id,status:'REVIEWED',note:'Evidence reviewed; no capital approval'},'network')).status,200);
w=await ws();const stale=w.revision;assert.equal((await command('config',{operation:'create',name:'Concurrency test',minimumScore:10,weights:w.configs[0].weights})).status,200);assert.equal((await req('config',{revision:stale,operation:'activate',id:w.configs[0].id},roles.admin)).status,409);
const audit=(await req('audit',undefined,roles.admin)).data.audit;for(const action of ['INCIDENTS_TRANSITION','RULES_ACTIVATE','CONFIG_ACTIVATE','SCORE_SAVED','IMPORTS_SAVED','CANDIDATE_EXPORTED','REVIEWS_TRANSITION'])assert.ok(audit.some(record=>record.action===action),action+' must be audited');
console.log('Domain API checks passed: roles, incident lifecycle, reviewed rules, historical evidence, model policy, sensitivity, canonical imports/quarantine/idempotency, candidate snapshots/exports, reviews and stale-write rejection.');
