import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const compile = path => ts.transpileModule(fs.readFileSync(path, 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2020 } }).outputText;
const url = source => `data:text/javascript;base64,${Buffer.from(source).toString('base64')}`;
const p = url(compile('src/domain/portfolio.ts'));
const i = url(compile('src/domain/investments.ts').replace("'./portfolio.js'", JSON.stringify(p)));
const { generateCandidates } = await import(i);
const { buildPortfolio } = await import(url(compile('src/data/portfolio.ts').replace("'../domain/portfolio.js'", JSON.stringify(p))));
const { allocateScenario, OBJECTIVES } = await import(url(compile('src/domain/scenarios.ts').replace("'./investments.js'", JSON.stringify(i))));
const candidates = generateCandidates(buildPortfolio(), '2026-09');
const input = { budget: 250000, objective: 'balanced', minimumScore: 10, mustFund: [], excluded: [], filters: { region: 'All', technology: 'All', state: 'All', period: '2026-09' } };
for (const objective of Object.keys(OBJECTIVES)) for (const budget of [0, 999, 12000, 250000, 10000000]) {
  const result = allocateScenario(candidates, { ...input, budget, objective });
  const selected = result.allocations.filter(value => value.selected);
  assert.ok(result.spend <= budget);
  assert.equal(result.spend + result.unallocated, budget);
  assert.equal(result.spend, selected.reduce((sum, value) => sum + value.cost, 0));
  assert.equal(new Set(selected.map(value => candidates.find(candidate => candidate.id === value.candidateId).siteId)).size, selected.length);
  assert.ok(selected.every(value => candidates.find(candidate => candidate.id === value.candidateId).eligible));
  assert.deepEqual(result, allocateScenario(result.candidates, result.input));
}
assert.equal(allocateScenario(candidates, { ...input, minimumScore: 100 }).spend, 0);
const good = candidates.find(candidate => candidate.eligible);
assert.throws(() => allocateScenario(candidates, { ...input, budget: 0, mustFund: [good.id] }), /infeasible/);
assert.throws(() => allocateScenario(candidates, { ...input, mustFund: [good.id], excluded: [good.id] }), /infeasible/);
assert.throws(() => allocateScenario(candidates, { ...input, mustFund: ['missing'] }), /unavailable/);
const pair = candidates.filter(candidate => candidate.eligible && candidate.siteId === good.siteId);
assert.ok(pair.length >= 2);
assert.throws(() => allocateScenario(candidates, { ...input, mustFund: pair.map(candidate => candidate.id) }), /alternative/);
const bad = candidates.find(candidate => !candidate.eligible);
assert.throws(() => allocateScenario(candidates, { ...input, mustFund: [bad.id] }), /infeasible/);
assert.throws(() => allocateScenario(candidates, { ...input, budget: -1 }), /Money/);
assert.throws(() => allocateScenario(candidates, { ...input, budget: 1.001 }), /Money/);
assert.throws(() => allocateScenario(candidates, { ...input, objective: 'unknown' }), /objective/);
assert.throws(() => allocateScenario(candidates, { ...input, minimumScore: NaN }), /Minimum/);
const mixed = structuredClone(candidates); mixed[0].currency = 'ZAR';
assert.throws(() => allocateScenario(mixed, input), /incompatible/);
const restricted = allocateScenario(candidates, { ...input, filters: { ...input.filters, region: 'Harare' } });
assert.ok(restricted.allocations.filter(value => value.selected).every(value => candidates.find(candidate => candidate.id === value.candidateId).region === 'Harare'));
const stateRestricted = allocateScenario(candidates, { ...input, filters: { ...input.filters, state: 'Capacity constrained' } });
assert.ok(stateRestricted.allocations.filter(value => value.selected).every(value => candidates.find(candidate => candidate.id === value.candidateId).decisionState === 'Capacity constrained'));
const result = allocateScenario(candidates, input);
const preserved = JSON.stringify(result);
candidates[0].estimatedCost = 1;
input.budget = 0;
assert.equal(JSON.stringify(result), preserved);
console.log('Scenario invariants passed: budgets, eligibility, conflicts, infeasibility, objectives, constraints, monetary precision and immutable replay.');

