import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const base=process.env.BASE_URL||'http://127.0.0.1:5175';const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));fs.mkdirSync('artifacts/qa',{recursive:true});
try{
 await page.goto(base+'/?view=network');await page.getByLabel('Username',{exact:true}).fill('admin');await page.getByLabel('Password',{exact:true}).fill('netone-local-demo');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Network intelligence',exact:true}).waitFor();await page.getByLabel('Network site').selectOption('N005');await page.getByText('9,999',{exact:true}).waitFor();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});for(const view of ['network','incidents','regulatory','config','data','evidence','map','investments','scenarios']){await page.goto(base+'/?view='+view);await page.getByRole('button',{name:'Sign out',exact:true}).waitFor();const fit=await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);assert.ok(fit,`${view} overflow at ${width}`);await page.screenshot({path:`artifacts/qa/domains-${view}-${width}.png`,fullPage:true});}console.log('Domain screens fit',width);}
 await page.setViewportSize({width:390,height:1000});await page.goto(base+'/?view=investments');await page.getByLabel('Inspect candidate').selectOption({index:1});await page.getByRole('button',{name:'Save shared candidate evidence',exact:true}).click();await page.getByText(/Shared evidence .* saved/).waitFor();
 await page.goto(base+'/?view=evidence');const row=page.locator('.priority-preview').last();const ids=['PDF','CSV','JSON'];for(const format of ids){const [download]=await Promise.all([page.waitForEvent('download'),row.getByRole('button',{name:'Export card '+format,exact:true}).click()]);const bytes=fs.readFileSync(await download.path());if(format==='PDF')assert.equal(bytes.subarray(0,4).toString(),'%PDF');if(format==='JSON'){const data=JSON.parse(bytes);assert.equal(data.dataStatus,'SYNTHETIC');assert.equal(data.evidence.hash.length,64);}}
 await page.getByLabel('Decision review note').fill('Browser evidence review request');await row.getByRole('button',{name:'Submit candidate for review',exact:true}).click();await page.getByText(/candidate .* SUBMITTED/).last().waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('Mobile shared candidate evidence, PDF/CSV/JSON exports and review submission passed.');
}finally{await browser.close();}
