import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(String(error)));
try {
  await page.goto(process.env.BASE_URL || 'http://localhost:5174');
  await page.getByLabel('Username', { exact: true }).fill('finance');
  await page.getByLabel('Password', { exact: true }).fill('netone-local-demo');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'Capital priorities', exact: true }).click();
  await page.getByRole('heading', { name: 'Explain the priority before allocating capital' }).waitFor();
  const compare = page.getByRole('checkbox', { name: /^Compare / });
  const eligibleCount = await compare.count();
  assert.ok(eligibleCount > 2);
  await compare.nth(0).check();
  await compare.nth(1).check();
  const comparison = page.getByRole('region', { name: 'Intervention comparison' });
  assert.equal(await comparison.locator('.candidate-evidence').count(), 2);
  assert.equal(await comparison.locator('tbody tr').count(), 14);
  await page.getByRole('button', { name: 'Save local evidence snapshot' }).click();
  const snapshot = await page.evaluate(() => JSON.parse(localStorage.getItem('netone-investment-snapshot')));
  assert.equal(snapshot.candidates.length, 400);
  assert.ok(snapshot.candidates.some(candidate => candidate.score !== null));
  await page.getByRole('checkbox', { name: 'Show excluded candidates' }).check();
  while(await page.getByRole('button',{name:/Show more candidates/}).isVisible())await page.getByRole('button',{name:/Show more candidates/}).click();
  assert.equal(await compare.count(), 400);
  await page.getByLabel('Inspect candidate', { exact: true }).selectOption('N001:capacity:2026-09');
  assert.match(await page.locator('.investment-feature').innerText(), /missing utilisation, commercial or comparable traffic growth/);
  await page.locator('.model-config summary').click();
  await page.getByLabel('Demand pressure weight', { exact: true }).fill('100');
  assert.equal(await page.getByRole('button', { name: 'Apply demo weights' }).isDisabled(), true);
  for (const label of ['Traffic growth (month-on-month)', 'Commercial contribution', 'Reliability burden', 'Service risk', 'Operating burden', 'Strategic inclusion']) await page.getByLabel(`${label} weight`, { exact: true }).fill('0');
  await page.getByRole('button', { name: 'Apply demo weights' }).click();
  await page.getByRole('button', { name: 'Save local evidence snapshot' }).click();
  const changed = await page.evaluate(() => JSON.parse(localStorage.getItem('netone-investment-snapshot')));
  assert.equal(changed.weights.demand, 100);
  assert.notDeepEqual(changed.candidates.filter(candidate => candidate.eligible).map(candidate => candidate.id), snapshot.candidates.filter(candidate => candidate.eligible).map(candidate => candidate.id));
  await page.getByRole('button', { name: 'Restore default weights' }).click();
  await page.locator('.model-config summary').click();
  await page.getByRole('checkbox', { name: 'Show excluded candidates' }).uncheck();
  await page.getByLabel('Inspect candidate', { exact: true }).selectOption('');
  await page.getByLabel('Region', { exact: true }).selectOption('Harare');
  assert.ok(await compare.count() < eligibleCount);
  await page.locator('.site-link').first().click();
  await page.getByRole('region', { name: 'Site investment candidates' }).waitFor();
  await page.locator('.candidate-disclosure summary').first().click();
  assert.equal(await page.locator('.candidate-disclosure').first().locator('tbody tr').count(), 7);
  await page.getByRole('button', { name: 'Back to portfolio' }).click();
  await page.getByRole('button', { name: 'Reset filters' }).click();
  await page.reload();
  await page.getByRole('heading', { name: 'Explain the priority before allocating capital' }).waitFor();
  await page.getByRole('checkbox', { name: /^Compare / }).nth(0).check();
  await page.getByRole('checkbox', { name: /^Compare / }).nth(1).check();
  fs.mkdirSync('artifacts/qa', { recursive: true });
  await page.screenshot({ path: 'artifacts/qa/investments-desktop.png' });
  await comparison.screenshot({ path: 'artifacts/qa/investments-comparison.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await comparison.screenshot({ path: 'artifacts/qa/investments-mobile-comparison.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  assert.deepEqual(errors, []);
  console.log('Investment browser journey passed: ranking, comparison, exclusions, weight validation/change, saved evidence, filters, site scoring, reload and mobile.');
} finally { await browser.close(); }
