import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
const apiCalls = [];
page.on('pageerror', error => errors.push(String(error)));
page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/api/') && new URL(request.url()).pathname !== '/api/netone') apiCalls.push(request.url()); });
try {
  await page.goto(process.env.BASE_URL || 'http://localhost:5174');
  await page.getByLabel('Username', { exact: true }).fill('finance');
  await page.getByLabel('Password', { exact: true }).fill('netone-local-demo');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('heading', { name: 'Where should the next dollar go?' }).waitFor();
  assert.equal(await page.locator('tbody tr').count(), 100);
  const allCapex = await page.getByRole('button', { name: /Capital deployed/ }).innerText();
  await page.getByLabel('Region', { exact: true }).selectOption('Bulawayo');
  assert.equal(await page.locator('tbody tr').count(), 20);
  const regionCapex = await page.getByRole('button', { name: /Capital deployed/ }).innerText();
  assert.notEqual(allCapex, regionCapex);
  await page.getByLabel('Technology', { exact: true }).selectOption('4G');
  assert.ok(await page.locator('tbody tr').count() < 20);
  assert.ok((await page.locator('tbody tr td:nth-child(2)').allTextContents()).every(value => value === '4G'));
  await page.locator('.site-link').first().click();
  await page.getByRole('article', { name: 'Site investment case' }).waitFor();
  await page.getByRole('heading', { name: 'Financial evidence' }).waitFor();
  await page.getByLabel('Reporting month').selectOption('2026-08');
  assert.match(await page.getByRole('article').innerText(), /2026-08/);
  await page.goBack();
  await page.getByRole('heading', { name: 'Where should the next dollar go?' }).waitFor();
  await page.getByRole('button', { name: 'Reset filters' }).click();
  await page.getByRole('button', { name: /^N001/ }).click();
  assert.match(await page.getByRole('article').innerText(), /Unavailable/);
  await page.reload();
  await page.getByRole('article', { name: 'Site investment case' }).waitFor();
  await page.getByRole('button', { name: 'Back to portfolio' }).click();
  await page.getByRole('button', { name: 'Investment map', exact: true }).click();
  await page.locator('.maplibregl-canvas').waitFor();
  assert.equal(await page.locator('.tower-marker').count(), 100);
  await page.getByLabel('Region', { exact: true }).selectOption('Bulawayo');
  assert.equal(await page.locator('.tower-marker').count(), 20);
  await page.getByRole('button', { name: /Open N002,/ }).click();
  await page.getByRole('article', { name: 'Site investment case' }).waitFor();
  await page.getByRole('button', { name: 'Executive portfolio', exact: true }).click();
  fs.mkdirSync('artifacts/qa', { recursive: true });
  await page.screenshot({ path: 'artifacts/qa/netone-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/qa/netone-mobile.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'page must not overflow horizontally');
  assert.deepEqual(apiCalls, [], 'synthetic milestone must not call inherited APIs');
  assert.deepEqual(errors, []);
  console.log('NetOne journey passed: filters and totals, site evidence, periods, back navigation, missing data, deep-link reload, map drill-down, mobile layout and no legacy API calls.');
} finally { await browser.close(); }
