import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const base=process.env.BASE_URL||'http://127.0.0.1:5177',browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));fs.mkdirSync('artifacts/qa',{recursive:true});
try{
await page.goto(base+'/?view=sites');await page.getByLabel('Username',{exact:true}).fill('admin');await page.getByLabel('Password',{exact:true}).fill('netone-local-demo');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:/N078 ·/}).first().waitFor();await page.getByRole('button',{name:/N078 ·/}).first().click();await page.getByText('2.25% · COMPARABLE',{exact:true}).waitFor();assert.ok(!(await page.locator('main').innerText()).includes('13% monthly demand'));await page.getByRole('link',{name:'Open cell QoS evidence and corrective alternatives'}).click();await page.getByRole('heading',{name:'Service assurance and corrective investment'}).waitFor();
await page.getByRole('button',{name:'Cell QoS evidence',exact:true}).click();await page.getByRole('button',{name:'Evaluate supplied evidence',exact:true}).click();await page.getByText('Saved synthetic evidence and server-attributed audit.',{exact:true}).waitFor();await page.getByText(/N078 · QOS-DSASR v.*INSUFFICIENT_EVIDENCE/).first().waitFor();
await page.getByRole('button',{name:'Corrective cases',exact:true}).click();await page.getByText(/Measured outcome 98%/).waitFor();await page.getByLabel('Assurance note').fill('Browser synthetic correction review; missing cause requires diagnosis');await page.getByRole('button',{name:'Create draft corrective case',exact:true}).click();await page.getByRole('heading',{name:'N078 · DRAFT',exact:true}).first().waitFor();let panel=page.locator('section').filter({has:page.getByRole('heading',{name:'N078 · DRAFT',exact:true})}).first();await panel.getByRole('button',{name:'Submit for investment review',exact:true}).click();await page.getByText(/Review readiness requires/).waitFor();await panel.getByText('Diagnosis and evidence',{exact:true}).click();await panel.getByLabel('Diagnosis cause',{exact:true}).selectOption('POWER');await panel.getByLabel('Diagnosis status',{exact:true}).selectOption('CONFIRMED');await panel.getByLabel('Diagnosis evidence references',{exact:true}).fill('SYNTHETIC-BROWSER-ENGINEERING-ASSESSMENT');await panel.getByRole('button',{name:'Save diagnosis',exact:true}).click();await page.getByRole('heading',{name:'N078 · DIAGNOSIS',exact:true}).first().waitFor();
for(const width of [390,1440]){await page.setViewportSize({width,height:1000});for(const tab of ['Obligation register','Cell QoS evidence','Corrective cases','Data governance']){await page.getByRole('button',{name:tab,exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),tab+' overflow');await page.screenshot({path:'artifacts/qa/pilot-'+tab.replaceAll(' ','-')+'-'+width+'.png',fullPage:true})}}
await page.setViewportSize({width:390,height:1000});await page.goto(base+'/?view=scenarios');await page.getByRole('button',{name:'Compare Balanced / Growth / Reliability',exact:true}).waitFor();await page.getByRole('button',{name:'Compare Balanced / Growth / Reliability',exact:true}).click();await page.getByRole('heading',{name:'Same-evidence budget trade-offs',exact:true}).waitFor();await page.getByRole('button',{name:'Run scenario',exact:true}).click();await page.getByRole('heading',{name:'Proposed allocation',exact:true}).waitFor();await page.getByText('Why leading priority candidates were omitted',{exact:true}).last().click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'artifacts/qa/pilot-budget-390.png',fullPage:true});
await page.route('https://tile.openstreetmap.org/**',route=>route.abort());await page.goto(base+'/?view=map');await page.getByLabel('Region',{exact:true}).selectOption('Manicaland');await page.getByRole('heading',{name:'Regional evidence fallback',exact:true}).waitFor({timeout:15000});assert.equal(await page.locator('.investment-map').isVisible(),false);await page.getByText('Manicaland · 20 fictional sites',{exact:true}).click();await page.getByRole('button',{name:'Retry map imagery',exact:true}).waitFor();const marker=page.getByRole('button',{name:/N078 · Capacity/}).first();await marker.focus();await page.keyboard.press('Enter');await page.getByRole('heading',{name:/N078 · Manicaland demonstration/}).waitFor();await page.screenshot({path:'artifacts/qa/pilot-map-fallback-390.png',fullPage:true});assert.deepEqual(errors,[]);console.log('Pilot browser passed: N078 growth, insufficient cell evidence, explicit draft/diagnosis and submission gating, retained outcomes, mobile/desktop assurance screens, same-evidence trade-offs, regional map fallback and keyboard site access.');
}finally{await browser.close()}

