import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(String(error)));
try {
  await page.goto(process.env.BASE_URL || 'http://localhost:5174');
  await page.getByLabel('Username', { exact: true }).fill('finance');
  await page.getByLabel('Password', { exact: true }).fill('netone-local-demo');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'Capital scenarios', exact: true }).click();
  const balancedName = 'Balanced ' + Date.now(); const growthName = 'Growth ' + Date.now();
  const initialCount = await page.evaluate(async () => (await (await fetch('/api/netone?action=scenarios')).json()).scenarios.length);
  await page.getByRole('button', { name: 'Run scenario', exact: true }).click();
  await page.getByRole('region', { name: 'Scenario result' }).waitFor();
  await page.getByLabel('Scenario name', { exact: true }).fill(balancedName);
  await page.getByRole('button', { name: 'Save scenario on server' }).click();
  await page.getByLabel('Scenario objective', { exact: true }).selectOption('growth');
  await page.getByRole('button', { name: 'Run scenario', exact: true }).click();
  await page.getByRole('region', { name: 'Scenario result' }).waitFor();
  await page.getByLabel('Scenario name', { exact: true }).fill(growthName);
  await page.getByRole('button', { name: 'Save scenario on server' }).click();
  await page.getByRole('checkbox', { name: `Compare scenario ${growthName}`, exact: true }).waitFor();
  const records = await page.evaluate(async () => (await (await fetch('/api/netone?action=scenarios')).json()).scenarios.slice(-2));
  assert.equal(records.length, 2);
  assert.ok(records.every(record => record.result.spend <= record.result.input.budget));
  assert.notDeepEqual(records[0].result.allocations.filter(a => a.selected).map(a => a.candidateId), records[1].result.allocations.filter(a => a.selected).map(a => a.candidateId));
  await page.getByRole('checkbox', { name: `Compare scenario ${balancedName}` }).check();
  await page.getByRole('checkbox', { name: `Compare scenario ${growthName}` }).check();
  await page.getByRole('region', { name: 'Scenario comparison' }).waitFor();
  await page.getByRole('button', { name: 'Verify replay' }).first().click();
  assert.match(await page.locator('main').innerText(), /Snapshot replay matches/);
  await page.getByLabel('Capital budget', { exact: true }).fill('0');
  await page.getByRole('button', { name: 'Run scenario', exact: true }).click();
  assert.match(await page.getByRole('region', { name: 'Scenario result' }).innerText(), /Spent \$0/);
  await page.getByText('Must-fund and exclusion constraints', { exact: true }).click();
  const candidateId = await page.getByLabel('Must fund', { exact: true }).locator('option').first().getAttribute('value');
  await page.getByLabel('Must fund', { exact: true }).selectOption(candidateId);
  await page.getByRole('button', { name: 'Run scenario', exact: true }).click();
  assert.match(await page.getByRole('alert').innerText(), /infeasible/);
  assert.equal(await page.getByRole('region', { name: 'Scenario result' }).count(), 0);
  await page.reload();
  await page.getByRole('button', { name: 'View saved result' }).first().waitFor();
  assert.equal(await page.getByRole('button', { name: 'View saved result' }).count(), initialCount + 2);
  await page.getByRole('button', { name: 'View saved result' }).first().click();
  assert.match(await page.getByRole('region', { name: 'Scenario result' }).innerText(), /Budget \$250,000/);
  fs.mkdirSync('artifacts/qa', { recursive: true });
  await page.screenshot({ path: 'artifacts/qa/scenarios-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/qa/scenarios-mobile.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  assert.deepEqual(errors, []);
  console.log('Scenario browser journey passed: allocation, objective changes, saving, comparison, replay, zero budget, infeasibility, reload and mobile.');
} finally { await browser.close(); }
