import { DATASET_VERSION, decisionState, observation, reviewReason, usd } from '../../domain/portfolio';
import type { Period, Site } from '../../domain/portfolio';
import { generateCandidates, rankCandidates } from '../../domain/investments';
import type { Weights } from '../../domain/investments';
import { useWorkspace } from '../../components/WorkspaceProvider';
import { activeRules } from '../../domain/operations';
import { SiteNetworkEvidence } from '../operations/OperationsWorkbench';
import { CandidateEvidence } from '../investments/InvestmentPriorities';
export default function SiteInvestmentCase({ site, period, onBack, weights }: { site: Site; period: Period; onBack: () => void; weights: Weights }) {
  const {workspace}=useWorkspace();const serviceRule=activeRules(workspace.rules,period).find(rule=>rule.metric==='availability'&&rule.comparator==='<')||null;
  const row = observation(site, period);
  const candidates = rankCandidates(generateCandidates([site], period, weights, serviceRule));
  const recommendation = candidates.find(candidate => candidate.eligible);
  return <article aria-label="Site investment case">
    <button className="text-button" onClick={onBack}>← Back to portfolio</button>
    <div className="page-heading"><div><p className="eyebrow">SITE INVESTMENT CASE · SYNTHETIC</p><h2>{site.id} · {site.name}</h2><p>{site.region} · {site.technology} · Radio access site · {site.strategic ? 'Inclusion coverage' : 'Standard strategic classification'}</p></div><span className="state-label">{decisionState(site, row)}</span></div>
    <section className="case-decision"><p className="eyebrow">ADVISORY DEMO INVESTMENT CASE</p><h3>{recommendation ? `${recommendation.action} · ${recommendation.score!.toFixed(2)} / 100 priority` : reviewReason(site, row)}</h3><p>{recommendation ? recommendation.reason : 'No eligible scored intervention with current evidence and demo rules.'} Evidence quality: <strong>{row.quality}</strong>.</p></section>
    <div className="mt-6"><SiteNetworkEvidence site={site}/></div><div className="case-grid">
      <section className="panel"><h3>Demand and reliability</h3><dl><dt>Reporting month</dt><dd>{period}</dd><dt>Utilisation</dt><dd>{row.utilisation === null ? 'Unavailable' : `${row.utilisation}%`}</dd><dt>Capacity headroom</dt><dd>{row.utilisation === null ? 'Unavailable' : `${100 - row.utilisation}%`}</dd><dt>Monthly demand growth</dt><dd>{row.growth}%</dd><dt>Availability</dt><dd>{row.availability.toFixed(1)}%</dd><dt>Faults in period</dt><dd>{row.faults}</dd></dl><p className="subtle">{row.quality === 'STALE' ? 'Utilisation was last observed in July 2026 and carried forward. Refresh before a capacity decision.' : row.quality === 'CONFLICT' ? 'Synthetic network sources disagree by 18 percentage points on utilisation. The displayed fixture value is unresolved.' : 'Synthetic aggregate observations for the selected month.'}</p></section>
      <section className="panel"><h3>Financial evidence</h3><dl><dt>Capital deployed at month end</dt><dd>{usd(row.capex)}</dd><dt>Monthly OPEX</dt><dd>{usd(row.opex)}</dd><dt>Monthly contribution proxy</dt><dd>{usd(row.contribution)}</dd><dt>Failure cost included in OPEX</dt><dd>{usd(row.failureCost)}</dd><dt>Currency and basis</dt><dd>USD · nominal demo values</dd></dl><p className="subtle">Contribution is a fictional commercial proxy, not measured revenue or validated profit. Missing values stay unavailable.</p></section>
      <section className="panel"><h3>Strategy and service evidence</h3><p>{site.strategic ? 'Demonstration inclusion tag: retain coverage considerations alongside commercial contribution.' : 'No special inclusion or critical-service tag in this fixture.'}</p><p className="subtle">The versioned demonstration availability rule is evaluated in each candidate below. No NetOne regulatory rule has been validated; these are service review prompts, not legal conclusions.</p><h3 className="mt-6">Observed movement</h3>{site.observations.map(metric => <p key={metric.period}>{metric.period}: {metric.utilisation === null ? 'Utilisation unavailable' : `${metric.utilisation}% utilisation`} · {metric.availability.toFixed(1)}% availability</p>)}</section>
      <section className="panel"><h3>Intervention history</h3>{site.history.map(item => <div className="history-item" key={item.date}><p className="eyebrow">{item.date} · DEMONSTRATION</p><h4>{item.action}</h4><p>{usd(item.cost)} · {item.outcome}</p></div>)}<h3 className="mt-6">Evidence provenance</h3><p className="subtle">Source: {DATASET_VERSION} / {site.id} / {period}. Stored in the shared canonical evidence workspace. All values are synthetic. No customer data or operator feeds are used.</p></section>
    </div>
    <section className="panel mt-6" aria-label="Site investment candidates"><h3>Interventions and score evidence</h3><p className="subtle">Alternative actions are not a combined programme. Scores express demo priority, not financial return.</p>{candidates.map(candidate => <details className="candidate-disclosure" key={candidate.id}><summary>{candidate.action} · {usd(candidate.estimatedCost)} · {candidate.score === null ? 'Excluded / score withheld' : `${candidate.score.toFixed(2)} / 100`}</summary><CandidateEvidence candidate={candidate} /></details>)}</section>
  </article>;
}
